theme: jekyll-theme-minimal
title: Laura Battaglia
tagline:     Probabilistic ML & Bayesian inference
affiliation: PhD Researcher, University of Oxford
# Exclude files not needed in the generated site
exclude:
  - index.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
